name: Deploy Static WebApp via Terraform

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read      # 👈 remove id-token: write to avoid OIDC

    steps:
      - uses: actions/checkout@v4

  name: Azure Login (Service Principal)
  uses: azure/login@v1
  with:
    creds: >
      {
        "clientId": "${{ secrets.ARM_CLIENT_ID }}",
        "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
        "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
        "tenantId": "${{ secrets.ARM_TENANT_ID }}",
        "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
        "resourceManagerEndpointUrl": "https://management.azure.com/",
        "managementEndpointUrl": "https://management.core.windows.net/"
      }

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'

      - name: Verify Azure Login
        run: az account show
